DROP TABLE IF EXISTS books CASCADING;
DROP TABLE IF EXISTS pages CASCADING;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author TEXT NOT NULL,
  title TEXT NOT NULL,
  genre TEXT NOT NULL
);

CREATE TABLE pages (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES books(id),
  number INT NOT NULL,
  text TEXT NOT NULL
)
